# Generated by Django 5.1.7 on 2025-03-08 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
    ]
