# Generated by Django 5.1.7 on 2025-03-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_rename_author_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#FF00FF", max_length=50),
        ),
    ]
