# Generated by Django 5.1.6 on 2025-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_author_news_image_news_original_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video_url',
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/'),
        ),
    ]
