# Generated by Django 5.1.7 on 2025-03-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
    ]
