# Generated by Django 5.1.7 on 2025-03-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True, related_name="news", to="news.sponsor"
            ),
        ),
    ]
